objects=\
color_distance_squared.o\
compute_disparity_map.o\
costCombined.o\
costLayer.o\
costVolume.o\
detect_occlusion.o\
disparityAW.o\
downsample_image.o\
downsample_image_dimensions.o\
downsample_image_int.o\
downsample_rgb_image.o\
downsample_rgb_image_int.o\
fill_occlusion_left_right.o\
fill_occlusion_right_left.o\
gaussian_blur_image.o\
gradient_x.o\
median.o\
median_histo.o\
normalize_image.o\
rgb_to_grayscale.o\
smooth_occlusion_weighted_median.o\
support.o\
weighted_histo.o\
weighted_median.o
